<?
$title="UBC Physics 102 (Summer 2003)";
$parent="../courses/index";
include 'head.php';
include 'url.php';
include 'math.php';
include 'menu.php';
?>

<center><h1>Electricity, Light and Radiation</h1></center>

<?	tochead(array('name'=>"News")); ?>

<?	tochead(array('name'=>"Wed&nbsp;Jul&nbsp;30", 'level'=>'3')); ?>
<ul><li>Your final grades have been submitted.  You can <a href="grades/index.html">check them here</a>.
</ul>

<?	tochead(array('name'=>"Older&nbsp;News", 'level'=>'3')); ?>
<dl>
<dt>Sun&nbsp;Jul&nbsp;27
	<dd>Your final grades will be posted here within a week.  Stay tuned!
<dt>Wed&nbsp;Jul&nbsp;23
	<dd>The <a href="tests/index.html">solutions to Test #3</a> have been posted.  I tallied the best 3 out of 4 and then scaled the marks by the formula
<table align="center" bgcolor="#ccddff"><tr>
	<td valign="bottom">Scaled Grade</td><td> = 30 <?=$times;?> (Raw Grade / 30)<sup>0.64</sup></td>
</td></tr></table>
to give an average of 21.5 (similar to the last midterm).  Your <a href="tests/index.html">individual marks</a> have also been posted in case you can't make it in to pick up your test on Thurs.
	<dd>Remember, the final exam will be held at 9am sharp on Fri Jul 25 in Hebb Theatre.  No exceptions.
	<dd>The web site will be down Fri evening and Sat morning.  Sorry.
<dt>Fri&nbsp;Jul&nbsp;18
	<dd>Test #3 will begin at <b>9:00am</b> on Mon, Jul 21.
	<dd>It is <b>your</b> responsibility to make sure you have completed all the labs.  You need to do <b>every</b> lab to pass the course.
<dt>Thu&nbsp;Jul&nbsp;17
	<dd>Test #2 has been marked and the <a href="tests/index.html">solutions posted</a>.  Each student's lowest scoring question was dropped and the remainder totalled out of 30.  The average was 21.4 (71%).
<dt>Mon&nbsp;Jul&nbsp;14
	<dd>Solutions to old practice problems are <a href="practice/index.html#Solutions">now available</a>.
<dt>Sat&nbsp;Jul&nbsp;12
	<dd>Some of the originally assigned practice problems have been removed because you will not be expected to be able to solve them. Check the <a href="practice/index.html#Schedule">Schedule</a>.
<dt>Fri Jul 11
	<dd>The solutions to <a href="tests/index.html">Test #1</a> have been posted.  The average mark was good, 82%, but the average on Q2+Q4 was 72%.  All questions on the next midterms and the final will be like Q2 and Q4 so expect the average to go down.
	<dd>The marks given are final!  The only exception is a marking mistake that cost you <b>2 or more</b> points.
	<dd>Midterm #2 will be on Mon, July 14 at <b>10:30am</b>.
<dt>Wed Jul 9
	<dd>Since I don't have time for office hours I will stay after class 11:30-12:30 every Wed & Thu.
	<dd><a href="http://students.ubc.ca/calendar/summer/dates.cfm?page=drop">Today</a> is the last day available for course withdrawals with &quot;W&quot; standing.
<dt>Mon Jul 7
	<dd>The <a href="lab/index.html#Schedule">labs have been re-ordered</a> so that Group B isn't always stuck doing labs on unfamiliar material.  Now the sequences are: Group A=1,2,4,3,5,6 and Group B=2,1,3,4,6,5. 
	<dd>If you want me to go through a practice problem ask me during class or <a href="practice/index.html#Requests">submit a request</a> before 6pm and I will cover it in the next class.
<dt>Fri Jul 3
	<dd>Midterm Tests #1 and #2 will begin at <b>10:30am</b> to accommodate student registration.  I won't answer <b><u>any</u></b> questions relating to the tested material on Mon, before the test is given.
	<dd>Midterm Test #3 will begin at <b>9:00am</b>.
<dt>Fri Jun 27
	<dd>The lab groups have been assigned.  <a href="lab/index.html#Groups">Check the list</a> so you can prepare for the first experiment.
<dt>Tue Jun 24
	<dd>The tutorial TAs have agreed to stay behind (up to) half an hour after the tutorials (Tue-Fri) to help students with practice problems.
<dt>Mon Jun 23
	<dd>Your lab group assignment (A or B) will be posted outside the lab (Hebb 20) near the beginning of the term. Go find out which group you belong to so that you can prepare for the first experiment.
<dt>Tue Jun 3
	<dd>Final exam set for Fri Jul 25 (in class).
<dt>Mon Apr 14
	<dd>PRS registration page ready.  <a href="prs/index.html">Register your transmitter now!</a>
<dt>Sun Mar 2
	<dd>Class is scheduled to begin Wed Jul 2.
</dl>

<?	tochead(array('name'=>"General&nbsp;Information")); ?>

<?	tochead(array('name'=>"Course&nbsp;Description", 'level'=>'3')); ?>

<p>Introduction to electricity and magnetism, electric circuits, radioactivity, including biological applications.</p>

<p>Credits: 3</p>

<p>Pre-reqs: PHYS 101.</p>

<p>Co-reqs: One of MATH 101, MATH 103, MATH 105, MATH 121.</p>

<p>Web page: <b><?=url(array('name'=>"http://www.zoology.ubc.ca/~rikblok/phys102/")); ?></b></p>

<?	tochead(array('name'=>"Textbook", 'level'=>'3')); ?>

<p><a href="http://www.prenhall.com/giancoli/">Physics for Scientists and Engineers (with modern physics)</a>, <I>by</I> Douglas C. Giancoli (Third Edition)</p>

<?	tochead(array('name'=>"PRS", 'level'=>"3", 'href'=>"prs/index.html")); ?>

<p><a href="prs/index.html">PRS</a> clickers will be used for in-class questions during lectures. Correct answers will score two points and wrong answers will score one point. <b>Be sure to <a href="prs/index.html">register</a> your PRS as soon as possible and bring it to every class.</b></p>

<?	tochead(array('name'=>"Mark&nbsp;Distribution", 'level'=>'3')); ?>

<p>To pass PHYS 102, the student must (1) obtain a passing grade for the final exam and (2) pass the laboratory component of the course. The mark distribution is:</p>

<table cellspacing="4" cellpadding="4" align="center"></tr><tr bgcolor="#ccddff">
	<td>Final Exam</td>		<td align="right">40 to 55</td>
</tr><tr bgcolor="#99ccff">
	<td>Weekly Tests</td>	<td align="right">25</td>
</tr><tr bgcolor="#ccddff">
	<td>Tutorials</td>		<td align="right">up to 10</td>
</tr><tr bgcolor="#99ccff">
	<td>PRS</td>			<td align="right">up to&nbsp;&nbsp;5</td>
</tr><tr bgcolor="#ccddff">
	<td>Labs</td>			<td align="right">20</td>
<tr bgcolor="#6699ff">
	<td><b>Total</b></td>	<td align="right"><b>100</b></td>
</tr></table>                                       

<p>Tutorial and PRS grades will be used to reduce the weight of the final exam.  The intention is to allow you to make up for poor performance in the tutorials and PRS questions by doing well on the final.  The weight of the final exam is given by:</p>
<table align="center" bgcolor="#ccddff"><tr>
	<td>Final Exam weight</td><td> = 55 - 10<?=$times;?>(Tutorial score) - 5<?=$times;?>(PRS score).</td>
</td></tr></table>

<p>For example, if you received 70% on your tutorials and 80% on your PRS questions then your final exam would be worth</p>
<table align="center" bgcolor="#ccddff"><tr>
	<td valign="top" rowspan="2">Final Exam weight</td><td> = 55 - 10<?=$times;?>(.70) - 5<?=$times;?>(.80)</td>
</tr><tr>
	<td> = 44.</td>
</td></tr></table>

<?	include 'foot.php';	?>
