<?
$title="Personal Response System";
$parent="../index";
include 'head.php';
include '../menu.php';
include 'table.php';
?>

<?	tochead(array('name'=>"Information")); ?>

<p>You should have an Educue Personal Response System (PRS) transmitter for in-class questions. These are available at the bookstore (ask at the counter). They are also being used in some sections of  Physics 100, 101, and other courses in the Faculty of Science. They are $70 new ($35 buy-back), but you only need one!</p>

<p>Once you have your transmitter, you must register the six-digit ID number here so we can give you credit for your responses. <b>Please register before the term begins.</b></p>

<p>Participation in PRS questions is not mandatory, but will contribute up to 5% to your final grade.  If you choose not to participate the extra 5% can be made up on the final exam.  See the <a href="../index.html#Mark&nbsp;Distribution">mark distribution</a> for more details.</p>

<?	tochead(array('name'=>"Registration")); ?>

<center><form METHOD="POST" ACTION="http://www.zoology.ubc.ca/cgi-bin/formmail.pl">
<input type="hidden" name="recipient" value=""><? /* value="rikblok@shaw.ca" */ ?>
<input type=hidden name="subject" value="P102 PRS Registration">
<input type=hidden name="required" value="LastName,FirstName,StudentNumber,ClickerNumber">
<p>Registration form for EduCue Personal Response System
transmitters (a.k.a. "clickers")</p>
<p><font color="#FF0000">Please double-check your numbers
before hitting "send"!</font></p>
</center>
<table align="center" border="0"><tr><td align="right"><p><b>Family Name:&nbsp;</b><input name="LastName">
<p><b>Given Names (all):&nbsp;</b><input name="FirstName">
<p><b>Student# (eight digits):&nbsp;</b><input name="StudentNumber">
<p><b>Clicker# (six digits):&nbsp;</b><input name="ClickerNumber">
<p><b>E-mail address (optional):&nbsp;</b><input name="Email">
<br>&nbsp;
<p><input type="submit" value="Send form">
</td></tr></table>
</form>

<? /*
<?	tochead(array('name'=>"Registered&nbsp;Transmitters">

<p>After you have registered your transmitter the information will be manually checked and entered here.  Check back in a few days to confirm that your information was correctly recorded.</p>

<file include="clickers.hti">
*/ ?>
                                                    
<?	include 'foot.php';	?>                           
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    