baseURL = 'https://www.cs.ubc.ca/~rikblok/'
languageCode = 'en-us'
title = "Rik's Treehouse"
theme = ['hugo-theme-relearn', 'hugo-cite']


[params]
  math = true
  [params.author]
    email = 'rik.blok@ubc.ca'
    name = 'Rik Blok'
	phone = '604-736-6343'
  [params.page]
    showTableOfContents = true
  [params.sidebar]
    enable = true
    menu = "main,content,toc"
  [params.toc]
    sidebar = true

[markup]
  [markup.goldmark]
  [markup.goldmark.renderer]
	unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
