<?
$title="Project 2: Construction";
$parent="../index";
$icon="${basedir}images/ubc.gif";
include 'head.php';
include "../menu.php";
include "shortcut.php";
include "table.php";
include '../admin/breakdown.php';
include 'math.php';
include 'footnote.php';
?>

<p>Moved to <?=url(array('name'=>"http://www.intsci.ubc.ca/wiki/doku.php?id=courses:isci422:project2:start")); ?></p>

<?	include 'foot.php';	?>                           
                                                    