<?
$title="UBC ISCI 422: Models in Science";
$subtitle='Fall 2009 (2009w session)';
$parent="../courses/index";
$icon="${basedir}images/ubc.gif";
include 'head.php';
include 'math.php';
include 'menu.php';
include "table.php";
include 'footnote.php';
include 'admin/breakdown.php';
//include 'url.php';
 ?>

<p>Moved to <?=url(array('name'=>"http://www.intsci.ubc.ca/wiki/doku.php?id=courses:isci422:start")); ?></p>

<?	include 'foot.php';	?>
