<?
$title="Software";
$parent="../index";
$icon="${basedir}images/ubc.gif";
include 'head.php';
include "../menu.php";
include "shortcut.php";
include "table.php";
include 'url.php';
?>

You may choose to implement a computational simulation for <a href="../project2/index.html">Project 2</a>.  To aid you, some modeling environment packages are available.  These programs will be explored in seminars to familiarize you with their function.

<?	tochead(array('name'=>'NetLogo','href'=>'http://ccl.northwestern.edu/netlogo/'));	?>

<p><a href="http://ccl.northwestern.edu/netlogo/">NetLogo</a> is a programmable modeling environment for simulating natural and social phenomena. It is particularly well suited for modeling complex systems developing over time. Modelers can give instructions to hundreds or thousands of independent "agents" all operating concurrently. This makes it possible to explore the connection between the micro-level behavior of individuals and the macro-level patterns that emerge from the interaction of many individuals.

<p>The NetLogo software, models and documentation are distributed <font color='darkgreen'><b>free of charge</b></font> for use by the public to explore and construct models.

<?	tochead(array('name'=>'Working Model 2D'));	?>

<p><a href="http://workingmodel.design-simulation.com/WM2D/index.php">Working Model 2D</a> is a powerful, engineering tool for statics, dynamics, mechatronics, biomechanics, design, vibrations, and controls. A diverse set of drawing and mathematical tools enable students, educators, and engineers to rapidly build complex models simulating the physical world. Never before has it been so easy to set up an experiment and explore <i>what-if</i> scenarios.

<p>Working Model 2D is commercial software so it cannot be distributed freely.  However, if you would like to use this software to develop your model, please <?=mailto(array('name'=>'ask','link'=>'isci-422@interchange.ubc.ca'))?>: we have Working Model 2D preloaded on a few laptops and we may be able to loan one to you.

<?	include 'foot.php';	?>                           
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    