<?
$title="Administration";
$parent="../index";
$icon="${basedir}images/ubc.gif";
include 'head.php';
include "../menu.php";
include 'table.php';
include 'breakdown.php';

$timeperclass = 110;	// minutes per lecture/seminar

function writeline($line,&$depth,&$sumtime)
// called by week()
{
	$line = trim($line);
	if (!strlen($line))	return;
	$newdepth = strspn($line,'>');		// count leading '>'
	$line = substr($line,$newdepth);	// and remove them
	for (; $depth < $newdepth; $depth++) echo "<ol>";
	for (; $depth > $newdepth; $depth--) echo "</ol>";
	if (substr_count($line,'|')==0)	$line = '|' . $line;
	$line = str_replace('Assignment','<b>Assignment</b>',$line);
	$line = str_replace('Homework:','<b>Homework:</b>',$line);
	$line = str_replace('Prep:','<b>Prep:</b>',$line);
	$line = str_replace('Project','<b>Project</b>',$line);
	$line = str_replace('LSK 464','<b>LSK 464</b>',$line);
	list ($time, $do) = split('\|', $line);
	echo '<li>';
	if (strlen($time)) {
		echo "<small><small>($time min)</small></small> ";
		if (!$newdepth)	$sumtime += $time;
	}
	echo $do;
}

function autofilldue($class, $week, $startorend, $depth = 0, $sumtime = 0)
{
	global $due;
	if ($week < 10)	$week = '0' . $week;
	$class = $class . $week;
	foreach ($due as $key => $value) {
		if (ereg($class, $value) && ereg($startorend, $value)) {
			writeline('<b>' . $key . " due.</b>",$depth,$sumtime);
		}
	}

}

function showweeks() 
{
	for ($i = 0; $i <= 13; $i++)	showweek($i);
}

function showweek($num)
{
	global $timeperclass, $week;
	static $sectionnum = 0;
	
	// error trap
	if (!array_key_exists($num, $week))	return;
	
	// fill variables
	list($newsection,$dates,$lecsubject,$lecstuff, $semsubject,$semstuff) = $week[$num];
	
	if ($dates=='') {
		// default dates from week
		$dates = weekdates($num);
	}
	
	if ($newsection != '') {
		$sectionnum++;
		tochead(array('name'=>"Section $sectionnum: $newsection",'level'=>'2'));
	}

	tochead(array('name'=>"Week $num: " . prettydatetime($dates), 'level'=>'3')); 
	echo '<table width="100%" cellspacing="4" cellpadding="4" align="center">';
	trh();
	echo "<th width=\"50%\">Lecture<br>$lecsubject</th><th width=\"50%\">Seminar<br>$semsubject</th></tr>";
	trbgalt();
	echo "<td valign=\"top\"><ol>";
	$depth = 0;
	$sumtime = 0;

	// lecture items
	autofilldue('lec', $num, 'lec-start');
	autofilldue('lec', $num, 'Start of ');
	$li = split("\n",$lecstuff);
	foreach ($li as $item)	writeline($item,$depth,$sumtime);
	autofilldue('lec', $num, 'lec-end');
	autofilldue('lec', $num, 'End of ');

	echo "</ol>";
	$sumtime -= $timeperclass;
	if ($sumtime < 0) {
		echo "<font color=\"green\"><small><small>" . -$sumtime . " min remaining.</small></small></font>";
	}
	if ($sumtime > 0) {
		echo "<font color=\"red\"><b><small><small>Available time exceeded by $sumtime min.</small></small></b></font>";
	}
	echo "</td>";
	echo "<td valign=\"top\"><ol>";
	
	// seminar items
	autofilldue('sem', $num, 'sem[ab]*-start');
	autofilldue('sem', $num, 'Start of ');
	autofilldue('sem', $num, 'in class');
	$li = split("\n",$semstuff);
	$depth = 0;
	$sumtime = 0;
	foreach ($li as $item)	writeline($item,$depth,$sumtime);
	autofilldue('sem', $num, 'sem[ab]*-end');
	autofilldue('sem', $num, 'End of ');

	echo "</ol>";
	$sumtime -= $timeperclass;
	if ($sumtime < 0) {
		echo "<font color=\"green\"><small><small>" . -$sumtime . " min remaining.</small></small></font>";
	}
	if ($sumtime > 0) {
		echo "<font color=\"red\"><b><small><small>Available time exceeded by $sumtime min.</small></small></b></font>";
	}
	echo "</td>";
	echo '</tr></table>';
}
?>

<?	tochead(array('name'=>'Objectives'));	?>

<p>There are four primary goals for the course.  The student should be able to...
<ol><li>Define <i>science</i> and explain.
	<li>Define <i>scientific model</i> and explain.
	<li>Deconstruct a scientific model.
	<li>Construct a scientific model.
</ol>

<p>To achieve these goals the course will be divided into three sections.

<?
showweeks();

include 'foot.php';	
?>
