<?
$title="Formula Sheet";
$parent="../index";
include 'head.php';
include "../menu.php";
include "article.php";
?>

<?	tochead(array('name'=>"Comments")) ?>

<p>This formula sheet will be provided with all tests and the final exam. <b>No notes may be brought into the tests.</b>  The formula sheet is provided here to help you while studying.</p>

<p>The formula sheet is continually being revised.  Check back frequently for the latest version.</p>

<?
tochead(array('name'=>"Download"));

echo article(array(
	'pdf'=>"formulasheet.pdf",
	'title'=>"UBC Physics 102 Formula Sheet"
));
                                                    
include 'foot.php';	
?>
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    