<?
$title="Tests";
$parent="../index";
include 'head.php';
include 'table.php';
include_once 'shortcut.php';
include '../menu.php';
?>

<p><b>Three</b> in-class, 60-min. tests will be given on Mondays.  Student ID cards must be shown upon request.  <b><i>No make-up tests will be given.</i></b></p>

<p>A <a href="../formula/index.html">formula sheet</a> will be provided with each test. To prepare it is recommended that you do the <a href="../practice/index.html">practice problems</a> for the lectures covered.</p>

<?	tochead(array('name'=>"Schedule")); ?>

<p>Notice that Tests 1 and 2 have been pushed back to a 10:30am start in order to accommodate student registration.  Test 3 will begin at the start of class (9:00am).</p>

<table cellspacing="4" cellpadding="4" align="center"><tr bgcolor="#6699ff" align="center">
	<td><b>Test</b></td><td><b>Date</b></td><td><b>Time</td><td><b>Lectures<br>Covered</b></td><td><b>Text<br>Covered</b></td><td><b>Solutions</b></td><td><b>Average</b></td><td><b>Mark<br>Distribution</b></td><? /* <td><b>Grades</b></td> */ ?>
</tr><?=trbgalt(array('align'=>'center')); ?>
	<td>1</td>	<td>Mon Jul  7</td><td>10:30-11:30am</td><td><a href="../lecture/index.html#1">1-3</a></td><td>Ch 42-43</td><td><?=shortcut(array('file'=>"test1.pdf", 'icon'=>"${basedir}images/pdficon.gif", 'nodate'=>true)); ?></td><td>82%</td><td><a href="dist1.gif"><img src="dist1.gif" width="96" height="64" border="1"></a></td>
</tr><?=trbgalt(array('align'=>'center')); ?>
	<td>2</td>	<td>Mon Jul 14</td><td>10:30-11:30am</td><td><a href="../lecture/index.html#4">4-8</a></td><td>Ch 21-24</td><td><?=shortcut(array('file'=>"test2.pdf", 'icon'=>"${basedir}images/pdficon.gif", 'nodate'=>true)); ?></td><td>71%</td><td><a href="dist2.gif"><img src="dist2.gif" width="96" height="64" border="1"></a></td>
</tr><?=trbgalt(array('align'=>'center')); ?>
	<td>3</td>	<td>Mon Jul 21</td><td>&nbsp;9:00-10:00am</td><td><a href="../lecture/index.html#8">8-13</a></td><td>Ch 25-29</td><td><?=shortcut(array('file'=>"test3.pdf", 'icon'=>"${basedir}images/pdficon.gif", 'nodate'=>true)); ?></td><td>72%</td><td><a href="dist3.gif"><img src="dist3.gif" width="96" height="64" border="1"></a></td>
</tr></table>                                       
                                                    
<?	include 'foot.php';	?>                           
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    