<?
include 'function-pre.php';

$name="SetParam";

$declaration="
object.SetParam(name,value)
";

$parameters="
" . pt() . "object
" . pd() . "Required.  Always the name of a <tt>R2DToo.FrontEnd</tt> object.
" . pt() . "name
" . pd() . "Required.  The name of a model parameter (without the trailing <tt>[]</tt> properties, case insensitive).
" . pt() . "value
" . pd() . "Required.  The value to set the parameter to.
";

$returnValue="
Returns 1 on success, 0 on fail.
";

$remarks="
Attempts to set parameter <tt>name</tt>=<tt>value</tt>.  Performs no bounds or error checking on value except to ensure it is a number.
";

$example="
' [VBScript]

' load
Dim R2DToo
Set R2DToo = Wscript.CreateObject(\"R2DToo.FrontEnd\")

' demonstrate method
If R2DToo.SetParam(\"World Width\",128) Then
    WScript.Echo \"Success!\"
Else
	WScript.Echo \"Failed!\"
End If

' unload
Set R2DToo = nothing
";

$seeAlso="
" . ref("GetParam") . ".
";

include 'function-post.php';
?>
