<?
$title="Laboratory";
$parent="../index";
include 'head.php';
include "article.php";
include "../menu.php";
?>

<?	tochead(array('name'=>"Information")); ?>

<p>Labs are <b>compulsory</b>, unless a student has been granted an exemption. A missed lab has to be made up within two days.  <b><i>All labs must be completed to obtain credit for the course.</i></b></p>

<p>Each section will have two labs per week starting with L02 on Friday, July 4.  Each section will be divided into two <a href="#Groups">groups (A or B)</a>.  Two experiments will be running simultaneously in each lab and groups will alternate between them.  TAs will be assigned to odd (1,3,5) or even (2,4,6) experiments so you will alternate between them.  Labs are held in <b>Hebb 20</b>. </p>

<table cellspacing="4" cellpadding="8" align="center"><tr bgcolor="#6699ff" align="center">
	<td><b>Section</b></td><td><b>Days</b></td><td><b>Times</b></td><td><b>Supervisor</b></td><td><b>&quot;Odd&quot; TA</b></td><td><b>&quot;Even&quot; TA</b></td>
</tr><tr bgcolor="#ccddff" align="center">
	<td rowspan="2">L01</td><td>Mon</td><td>12:30-15:30</td><td>Dr. Rik Blok</td><td rowspan="3">Kat Dixon</td><td rowspan="3">Perry Sih</td>
</tr><tr bgcolor="#99ccff" align="center">
		<td>Wed</td><td>12:30-15:30</td><td>Dr. Evert Koster</td>
</tr><tr bgcolor="#ccddff" align="center">
	<td>L02</td><td>Tue Fri</td><td>12:30-15:30</td><td>Dr. Rik Blok</td>
</tr></table>

<p>Bring to your lab: Lab manual, yellow notebook, calculator and completed prelaboratory assignment.  (If you took PHYS 101 within the last year your notebook may still be in the lab for you to reuse.)  We will be reusing the 02W Edition of the Lab manual.</p>

<p>Before coming to the first lab be sure you have read the <i>General Introduction</i>, <i>Reference Sheet</i> and either <i>Experiment 1 or 2</i> (see <a href="#Groups">Groups</a>, below).  Make sure you understand how to do error analysis.</p>

<?	tochead(array('name'=>"Schedule")); ?>

<table cellspacing="4" cellpadding="4" align="center"><tr bgcolor="#6699ff" align="center">
	<td><b>Date</b></td><td><b>Section<br></td>	<td><b>Group A</b></td><td><b>Group B</b></td>	</tr><tr bgcolor="#ccddff" align="center">
	<td>Wed Jul  2</td>	<td><hr></td>	<td><hr></td>	<td><hr></td>
</tr><tr bgcolor="#99ccff" align="center">
	<td>Fri Jul  4</td>	<td>L02</td>	<td>1</td>	<td>2</td>
</tr><tr bgcolor="#ccddff" align="center">
	<td>Mon Jul  7</td>	<td>L01</td>	<td>1</td>	<td>2</td>
</tr><tr bgcolor="#99ccff" align="center">
	<td>Tue Jul  8</td>	<td>L02</td>	<td>2</td>	<td>1</td>
</tr><tr bgcolor="#ccddff" align="center">
	<td>Wed Jul  9</td>	<td>L01</td>	<td>2</td>	<td>1</td>
</tr><tr bgcolor="#99ccff" align="center">
	<td>Fri Jul 11</td>	<td>L02</td>	<td>4</td>	<td>3</td>
</tr><tr bgcolor="#ccddff" align="center">
	<td>Mon Jul 14</td>	<td>L01</td>	<td>4</td>	<td>3</td>
</tr><tr bgcolor="#99ccff" align="center">
	<td>Tue Jul 15</td>	<td>L02</td>	<td>3</td>	<td>4</td>
</tr><tr bgcolor="#ccddff" align="center">
	<td>Wed Jul 16</td>	<td>L01</td>	<td>3</td>	<td>4</td>
</tr><tr bgcolor="#99ccff" align="center">
	<td>Fri Jul 18</td>	<td>L02</td>	<td>5</td>	<td>6</td>
</tr><tr bgcolor="#ccddff" align="center">
	<td>Mon Jul 21</td>	<td>L01</td>	<td>5</td>	<td>6</td>
</tr><tr bgcolor="#99ccff" align="center">
	<td>Tue Jul 22</td>	<td>L02</td>	<td>6</td>	<td>5</td>
</tr><tr bgcolor="#ccddff" align="center">
	<td>Wed Jul 23</td>	<td>L01</td>	<td>6</td>	<td>5</td>
</tr></table>                                       
                                                    
<?	tochead(array('name'=>"Groups")); ?>

<p>Check the list below to find out which group (A or B) you belong to so that you can prepare for the first experiment.  Your group assignment will also be posted outside the lab (Hebb 20) near the beginning of the term.</p>

<?
echo article(array(
	'pdf'=>"LabGroups.pdf",
	'title'=>"Physics 102 (Summer 2003) Lab Groups.<br>July 2 Version.  Removals are in light gray, additions in bold black."
));
?>

<?	include 'foot.php';	?>                           
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    