<?
include 'function-pre.php';

$name="forEachNbrVar";

$declaration="
void __stdcall forEachNbrVar(
	int x,                                       // x-coordinate of agent
	int y,                                       // y-coordinate of agent
	bool (*func)(pState,int,int,pState*,         // name of function
	             int,int,double*,int),      
	double* var,                                 // workspace
	int varCount                                 // size of workspace
);
";

$parameters="
" . pt() . "x
" . pd() . "X-coordinate of agent whose neighbours are to be processed (zero based).
" . pt() . "y
" . pd() . "Y-coordinate of agent whose neighbours are to be processed (zero based).
" . pt() . "func
" . pd() . "The name of a function to apply to each agent in turn.
" . pt() . "var
" . pd() . "Allocated array of storage space for extra parameters.
" . pt() . "varCount
" . pd() . "Size of array, var[0..varCount-1].
";

$remarks="
This function is available through the API.  It provides an efficient way to process every neighbour to the agent at (<var>x,y</var>) in turn.  The details of this function are the same as that for " . ref("forEachAgentVar") . " except that the iteration is only over the neighbours of a single agent.
";

$example="
bool getBestScore(" . ref("pState") . " state, int x, int y,
                  " . ref("pState") . " *nbr, int nbrCount, int feaMode,
                  double *var, int varCount)
// score[0..width-1][0..height-1] is a matrix of doubles
{
    switch (feaMode) {
        case feaBegin:    var[0]=-1; var[1]=-1; break;
        case feaContinue: var[state[0]] = max(var[state[0]],score[x][y]);
    }
    return true;
}		
void __stdcall onTick(double &time)
{
    int x,y;
    int nbrCount;
    " . ref("pState") . " *nbr;
    " . ref("pState") . " state = anyAgent(NULL,x,y,nbr,nbrCount);
    double bestScore[2];
    forEachNbrVar(x,y,getBestScore,bestScore,2);
    // now do something about it...
}
";

$revisions="
API v1.5<ul><li>no longer passes <tt>param</tt> to <tt>func</tt>
	</ul>
";

$seeAlso="
" . ref("forEachAgentVar") . ", " . ref("forEachNbr") . ".
";

include 'function-post.php';
?>
